
import { FileHeart, FileText, Stethoscope, HeartPulse, Pill } from 'lucide-react';
import { type PDFDocumentData } from '@/app/types/pdf-document';
import { format } from 'date-fns';

export function PDFDocument({ id, fileName, analysis }: PDFDocumentData) {
  const { doctorSummary, patientSummary, lifestyleSuggestions, medicines, severity } = analysis;

  const severityConfig = {
    'Normal': 'text-green-600',
    'Needs Attention': 'text-yellow-600',
    'Immediate Action': 'text-red-600',
  };

  const Section = ({ title, icon, children }: { title: string, icon: React.ReactNode, children: React.ReactNode }) => (
    <div className="mb-8">
      <h2 className="text-2xl font-bold font-headline text-[#198a8c] flex items-center gap-2 mb-3 border-b-2 border-[#198a8c]/30 pb-2">
        {icon} {title}
      </h2>
      <div className="text-gray-800 text-base leading-relaxed whitespace-pre-wrap">
        {children}
      </div>
    </div>
  );

  return (
    <div id={id} className="bg-white text-[#333] p-12 font-body" style={{ width: '210mm' }}>
      <header className="mb-12 border-b-4 border-[#198a8c] pb-6">
        <div className="flex justify-between items-center">
          <div className='flex items-center gap-4'>
            <FileHeart className="w-16 h-16 text-[#198a8c]" />
            <div>
              <h1 className="text-4xl font-bold font-headline text-[#198a8c]">MediScan AI</h1>
              <p className="text-gray-600 text-lg">Medical Report Analysis</p>
            </div>
          </div>
          <div className="text-right">
             <p className="font-semibold text-gray-700">{fileName}</p>
             <p className="text-sm text-gray-500">Analysis Date: {format(new Date(), 'MMM dd, yyyy')}</p>
          </div>
        </div>
      </header>

      <main>
        <div className="bg-gray-50 p-6 rounded-lg mb-8 border border-gray-200">
            <h3 className="text-xl font-semibold mb-2">Overall Assessment</h3>
            <p className={`text-lg font-bold ${severityConfig[severity]}`}>{severity}</p>
            <p className="text-gray-600">This assessment is based on the AI's interpretation of the provided medical report.</p>
        </div>

        <Section title="Patient-Friendly Summary" icon={<FileText />}>
          <p>{patientSummary}</p>
        </Section>

        <Section title="Doctor-Style Summary" icon={<Stethoscope />}>
          <p className="font-mono text-sm bg-gray-100 p-4 rounded-md border border-gray-200">{doctorSummary}</p>
        </Section>

        <Section title="Lifestyle & Health Suggestions" icon={<HeartPulse />}>
          <p>{lifestyleSuggestions}</p>
        </Section>

        <Section title="Medicine Suggestions" icon={<Pill />}>
          {medicines && medicines.disclaimer && (
            <p className="text-sm text-yellow-700 bg-yellow-100 border border-yellow-300 p-3 rounded-md mb-4">
              <strong>Disclaimer:</strong> {medicines.disclaimer}
            </p>
          )}
          {medicines && medicines.recommendations && medicines.recommendations.length > 0 ? (
            <ul className="space-y-4">
              {medicines.recommendations.map((med, index) => (
                <li key={index} className="flex flex-col p-3 border-l-4 border-[#198a8c] bg-gray-50 rounded-r-md">
                  <span className="font-bold text-lg text-gray-800">{med.medicineName}</span>
                  <span className="text-base text-gray-600">{med.reason}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-gray-500">No specific medicines were recommended based on this report.</p>
          )}
        </Section>
      </main>

      <footer className="mt-12 pt-6 border-t-2 border-gray-200 text-center text-gray-500 text-xs">
          <p>
            This report was generated by MediScan AI for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. 
            Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
          </p>
           <p className='mt-2 font-semibold'>&copy; {new Date().getFullYear()} MediScan AI</p>
      </footer>
    </div>
  );
}
